name: data-analysis
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:delegated
    restart: unless-stopped

  mariadb-master:
    build: mariadb-master
    container_name: mariadb-master
    env_file: local.env
    healthcheck:
      interval: 10s
      retries: 5
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "--ssl-ca=/etc/mysql/ssl/ca-cert.pem", "--ssl-cert=/etc/mysql/ssl/server-cert.pem", "--ssl-key=/etc/mysql/ssl/server-key.pem" ]
      timeout: 5s
    ports:
      - '3306:3306'
    restart: unless-stopped
    volumes:
      - ./certs/mariadb:/etc/mysql/ssl:ro
      - ./mariadb-master/conf/master.cnf:/etc/mysql/conf.d/master.cnf:ro
      - ./mariadb-master/data:/var/lib/mysql:delegated
      - ./mariadb-master/log:/var/log/mysql:delegated
      - ./mariadb-master/initdb:/docker-entrypoint-initdb.d:delegated

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    restart: unless-stopped
