[database]
host = localhost
user = root
password = password
database = data-analysis
port = 3306

[filtering]
allowed_emails = abrivat.dominique@castel-freres.com, abrivat@williampitters.com, c.canesson@castel-freres.com, canesson@castel-freres.com, canessonc@castel-freres.local, cc@solibra.ci, christophe.canesson@orange.fr, christophe.canesson@vins-castel.wine, codir@castel-corporate.com, d.abrivat@castel-freres.com, d.lioret@castel-freres.com, d.lioret@hotmail.com, dabrivat@castel-freres.com, dabrivat@mabriz.com, david.lioret@vins-castel.wine, dlioret@castel-freres.com, dlioret@hotmail.com, dlioret@mabriz.com, dominique.abrivat@bbox.fr, dominique.abrivat@castel-freres.com, dominique.abrivat@gmail.com, dominique.abrivat@orange.fr, dominique.abrivat@vins-castel.wine, foret.valerie@sfr.fr, foretv@castel-freres.local, gdc@castel-corporate.com, gregory.clerc@castel-corporate.com, l-dequatre@castel-corporate.com, l.dequatre@castel-corporate.com, lioret@castel-freres.com, lioretd@castel-freres.local, marco@castel-freres.local, marion@castelfrance.com.cn, marion@kriter.com, marion_1004@hotmail.fr, mo-de-toi@hotmail.fr, mpphmarion@neuf.fr, o-marc@castel-freres.com, o.marc@castel-freres.com, o_marc@castel-freres.com, olivier-marc@castel-freres.com, olivier.marc5617@gmail.com, olivier.marc@barton-guestier.com, olivier.marc@castel-freres.com, olivier.marc@kriter.com, olivier.marc@listel.fr, olivier.marc@patriarche.com, olivier.marc@vins-castel.wine, olivier_b_marc@yahoo.com, olivier_marc@castel-freres.com, olivier_marc@orange.fr, oliviermarc@castel-freres.com, omarc216@hotmail.com, omarc90@hotmail.com, omarc@castel-freres.com, omarc@castel-freres.fr, omarc@catel-freres.com, omarc@optiaccess.com, omarc@orange.fr, omarc@wanadoo.fr, p.marion@patriarche.com, pascal.favre@castel-corporate.com, philippe.marion@barton-gestier.com, philippe.marion@barton-guestier.com, philippe.marion@diageo.com, philippemarion@barton-guestier.com, phillipe.marion@barton-guestier.com, v.foret@castel-freres.com, valerie.costes@vins-castel.wine, valerie.foret@vins-castel.wine

[storage]
# Directory where extracted attachments will be stored
attachments_dir = ./data/attachments
eml_dir = ./data/eml

[neo4j]
uri = bolt://localhost:7687
user = neo4j
password = password

[openai]
api_key =
