UPDATE identity SET name ="Dominique ABRIVAT" WHERE email_address IN ("dominique.abrivat@bbox.fr", "dominique.abrivat@gmail.com", "dominique.abrivat@orange.fr", "dominique.abrivat@castel-freres.com", "dominique.abrivat@vins-castel.wine", "d.abrivat@castel-freres.com", "dabrivat@mabriz.com", "abrivat.dominique@castel-freres.com", "dabrivat@castel-freres.com", "abrivat@williampitters.com");
UPDATE identity SET name ="Christophe CANESSON" WHERE email_address IN ("christophe.canesson@orange.fr", "christophe.canesson@vins-castel.wine", "c.canesson@castel-freres.com", "cc@solibra.ci", "canesson@castel-freres.com", "canessonc@castel-freres.local");
UPDATE identity SET name ="Valérie COSTES-FORET" WHERE email_address IN ("valerie.costes@vins-castel.wine", "valerie.foret@vins-castel.wine", "v.foret@castel-freres.com", "foret.valerie@sfr.fr", "foretv@castel-freres.local");
UPDATE identity SET name ="David LIORET" WHERE email_address IN ("david.lioret@vins-castel.wine", "d.lioret@castel-freres.com", "d.lioret@hotmail.com", "lioret@castel-freres.com", "lioretd@castel-freres.local", "dlioret@hotmail.com", "dlioret@mabriz.com", "dlioret@castel-freres.com");
UPDATE identity SET name ="Olivier MARC" WHERE email_address IN ("mo-de-toi@hotmail.fr", "o.marc@castel-freres.com", "omarc216@hotmail.com", "omarc90@hotmail.com", "omarc@castel-freres.com", "omarc@castel-freres.fr", "omarc@catel-freres.com", "omarc@optiaccess.com", "omarc@orange.fr", "omarc@wanadoo.fr", "olivier.marc5617@gmail.com", "olivier.marc@barton-guestier.com", "olivier.marc@castel-freres.com", "olivier.marc@kriter.com", "olivier.marc@listel.fr", "olivier.marc@patriarche.com", "olivier.marc@vins-castel.wine", "o-marc@castel-freres.com", "olivier-marc@castel-freres.com", "oliviermarc@castel-freres.com", "olivier_b_marc@yahoo.com", "olivier_marc@castel-freres.com", "olivier_marc@orange.fr", "o_marc@castel-freres.com", "marco@castel-freres.local");
UPDATE identity SET name ="Philippe MARION" WHERE email_address IN ("marion@castelfrance.com.cn", "marion@kriter.com", "marion_1004@hotmail.fr", "mpphmarion@neuf.fr", "philippemarion@barton-guestier.com", "phillipe.marion@barton-guestier.com", "p.marion@patriarche.com", "philippe.marion@barton-gestier.com", "philippe.marion@barton-guestier.com", "philippe.marion@diageo.com");
UPDATE identity SET name ="CODIR" WHERE email_address IN ("codir@castel-corporate.com");
UPDATE identity SET name ="Guy DE CLERCQ" WHERE email_address IN ("gdc@castel-corporate.com", "gdc@bgi-corporate.com", "gdc@bgi-france.fr");
UPDATE identity SET name ="Gregory CLERC" WHERE email_address IN ("gregory.clerc@castel-corporate.com");
UPDATE identity SET name ="Pascal FAVRE" WHERE email_address IN ("pascal.favre@castel-corporate.com");
UPDATE identity SET name ="Laurence DEQUATRE" WHERE email_address IN ("l-dequatre@castel-corporate.com", "l.dequatre@castel-corporate.com");

